services:
  - type: web
    name: touchless-canteen
    env: python
    region: oregon
    plan: free
    runtime: python-3.10.13
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app